package my.chatapplication.Constant;

/**
 * Created by nasser on 22/07/15.
 */
public enum  VALIDATION {
    EMAIL_REQUIRED , PASSWORD_REQUIRED , REPASSWORD_REQUIRED ,
    NOT_MATCH_PASSWORD , EMAIL_INVALID , PASSWORD_INVALID , EMAIL_ALREADY_EXIST,
    TELEPHONE_NUMBER_REQUIRED , TELEPHONE_NUMBER_NVALID , NAME_REQUIRED
    ,TRY_AGAIN_LATER ,
    ACCEPTED
}
